### ISSUE TITLE
Erro login-banco de dados

### ISSUE THREAD

**Issue by MarinaFFSC** [bela975/PETracker#5]
![WhatsApp Image 2023-05-14 at 15 48 23](https://github.com/bela975/PETracker/assets/115357002/a8a1fe59-321d-4842-8a4f-707e6c9e3aab)
Está parte do código está apresentando Erro no login com integração no banco de dados, o que ocasiona no usuário sempre precisar  criar um superuser no VS novo.

**Comment by virnaamaral** [comment]
Resolvido. Bastava dar python manage.py makemigrations e python manage.py migrate.
